"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-09-26 15:50:03.161820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins')),
    sa.UniqueConstraint('login', name=op.f('uq_admins_login'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_ts'), 'audit_log', ['ts'], unique=False)
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('ssh_port', sa.Integer(), nullable=False),
    sa.Column('ssh_user', sa.String(length=64), nullable=False),
    sa.Column('ssh_secret_enc', sa.Text(), nullable=False),
    sa.Column('host_key', sa.Text(), nullable=True),
    sa.Column('enabled_for_users', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('prepared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ok_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_servers'))
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=8), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("subject IN ('admin', 'user')", name=op.f('ck_sessions_subject')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessions_token_hash'))
    )
    op.create_index('ix_sessions_subject', 'sessions', ['subject', 'subject_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('login', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('blocked_by', sa.String(length=16), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_configs', sa.Integer(), nullable=False),
    sa.Column('deleting_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("blocked_by IN ('admin', 'expiry')", name=op.f('ck_users_blocked_by')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('login', name=op.f('uq_users_login'))
    )
    op.create_table('configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('container', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('material_enc', sa.Text(), nullable=True),
    sa.Column('blocked_by', sa.String(length=16), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_rx', sa.BigInteger(), nullable=True),
    sa.Column('last_tx', sa.BigInteger(), nullable=True),
    sa.Column('counter_session', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("blocked_by IN ('user', 'admin')", name=op.f('ck_configs_blocked_by')),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_configs_server_id_servers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_configs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configs')),
    sa.UniqueConstraint('server_id', 'container', 'client_id', name=op.f('uq_configs_server_id_container_client_id'))
    )
    op.create_index(op.f('ix_configs_server_id'), 'configs', ['server_id'], unique=False)
    op.create_index(op.f('ix_configs_user_id'), 'configs', ['user_id'], unique=False)
    op.create_table('invite_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_invite_keys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invite_keys')),
    sa.UniqueConstraint('key_hash', name=op.f('uq_invite_keys_key_hash'))
    )
    op.create_index(op.f('ix_invite_keys_user_id'), 'invite_keys', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedupe_key', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=8), server_default='queued', nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'running', 'done', 'failed')", name=op.f('ck_jobs_status')),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_jobs_server_id_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index('ix_jobs_claim', 'jobs', ['status', 'run_after'], unique=False)
    op.create_index('uq_jobs_active_dedupe', 'jobs', ['dedupe_key'], unique=True, postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.create_table('server_containers',
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('container', sa.String(length=64), nullable=False),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_server_containers_server_id_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('server_id', 'container', name=op.f('pk_server_containers'))
    )
    op.create_table('traffic_daily',
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('rx', sa.BigInteger(), nullable=False),
    sa.Column('tx', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['configs.id'], name=op.f('fk_traffic_daily_config_id_configs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('config_id', 'day', name=op.f('pk_traffic_daily'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traffic_daily')
    op.drop_table('server_containers')
    op.drop_index('uq_jobs_active_dedupe', table_name='jobs', postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.drop_index('ix_jobs_claim', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_invite_keys_user_id'), table_name='invite_keys')
    op.drop_table('invite_keys')
    op.drop_index(op.f('ix_configs_user_id'), table_name='configs')
    op.drop_index(op.f('ix_configs_server_id'), table_name='configs')
    op.drop_table('configs')
    op.drop_table('users')
    op.drop_index('ix_sessions_subject', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('servers')
    op.drop_index(op.f('ix_audit_log_ts'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('admins')
    # ### end Alembic commands ###
